sudo: required
dist: trusty

services : docker

install:
  # Update docker-engine using Ubuntu 'trusty' apt repo
  - sudo curl -L "https://github.com/docker/compose/releases/download/1.22.0/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
  - docker-compose version

before_script:
  - docker-compose build 

script:
  - docker-compose up

after_script:
  - docker-compose down
